# Generated by Django 3.2.25 on 2026-05-29 21:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0013_generatecsvlogrequest_allow_null_timestamps"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contentsummarylog",
            index=models.Index(
                fields=["content_id", "user"], name="contentsummarylog_cid_user"
            ),
        ),
    ]
