# Generated by Django 3.2.25 on 2026-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0048_localfile_file_size_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="included_categories",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="included_grade_levels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="included_learning_activities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
